# Generated by Django 5.1.1 on 2024-10-31 02:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField()),
                (
                    "brand",
                    models.CharField(
                        choices=[("apple", "Apple"), ("samsung", "Samsung")],
                        max_length=32,
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[
                            ("ip11", "iPhone 11"),
                            ("ip12", "iPhone 12"),
                            ("ip12p", "iPhone 12 Pro"),
                            ("ip12pm", "iPhone 12 Pro Max"),
                            ("ip13", "iPhone 13"),
                            ("ip13p", "iPhone 13 Pro"),
                            ("ip13pm", "iPhone 13 Pro Max"),
                            ("ip14", "iPhone 14"),
                            ("ip14p", "iPhone 14 Pro"),
                            ("ip14pm", "iPhone 14 Pro Max"),
                            ("gs20", "Galaxy S20"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "storage_capacity",
                    models.CharField(
                        choices=[
                            ("64", "64GB"),
                            ("128", "128GB"),
                            ("256", "256GB"),
                            ("512", "512GB"),
                            ("1024", "1TB"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "carrier",
                    models.CharField(choices=[("unlocked", "Unlocked")], max_length=32),
                ),
                (
                    "battery_health",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                (
                    "screen",
                    models.CharField(
                        choices=[
                            ("cracked", "Dañada"),
                            ("used", "Aceptable"),
                            ("good", "Buena"),
                            ("flawless", "Impecable"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "sidesAndBack",
                    models.CharField(
                        choices=[
                            ("cracked", "Dañada"),
                            ("used", "Aceptable"),
                            ("good", "Buena"),
                            ("flawless", "Impecable"),
                        ],
                        max_length=32,
                    ),
                ),
                ("fullyFunctional", models.BooleanField()),
                ("repaired", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listed_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("shipping_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ml", "Mercado Libre"),
                            ("fb", "Facebook Marketplace"),
                        ],
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log",
                        to="inventory_management.product",
                    ),
                ),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listed_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("shipping_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ml", "Mercado Libre"),
                            ("fb", "Facebook Marketplace"),
                        ],
                        max_length=32,
                    ),
                ),
                ("buyout_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estimated_sale_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("seller", models.CharField(max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="inventory_management.product",
                    ),
                ),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("listed_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("shipping_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("ml", "Mercado Libre"),
                            ("fb", "Facebook Marketplace"),
                        ],
                        max_length=32,
                    ),
                ),
                ("buyout_price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "estimated_sale_price",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("seller", models.CharField(max_length=180)),
                ("sale_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("buyer", models.CharField(max_length=180)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales",
                        to="inventory_management.product",
                    ),
                ),
            ],
            options={
                "ordering": ["updated_at"],
            },
        ),
    ]
