# Generated by Django 5.1.1 on 2024-11-05 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory_management",
            "0002_brand_carrier_condition_storage_remove_product_brand_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="screen_condition",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Pantalla"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screen_products",
                to="inventory_management.condition",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sides_and_back_condition",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"category": "Lados y tapa"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sides_back_products",
                to="inventory_management.condition",
            ),
        ),
    ]
