# Generated by Django 4.1 on 2024-11-09 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0003_alter_product_screen_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='is_listed',
            field=models.BooleanField(default=False),
        ),
    ]
