# Generated by Django 4.1 on 2024-11-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0004_inventory_is_listed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lifecycle_stage',
            field=models.CharField(choices=[('log', 'Log'), ('inventory', 'Inventory'), ('sale', 'Sale')], default='log', max_length=20),
        ),
    ]
