# Generated by Django 4.1 on 2024-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0005_product_lifecycle_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='buyer',
            field=models.CharField(blank=True, max_length=180, null=True),
        ),
    ]
