# Generated by Django 5.1.1 on 2024-09-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_tracking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank", "Bank")],
                default="bank",
                max_length=7,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="income",
                max_length=7,
            ),
            preserve_default=False,
        ),
    ]
