# Generated by Django 5.1.1 on 2024-10-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_tracking", "0002_remove_transaction_credit_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank", "Bank")],
                default="cash",
                max_length=4,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
