# Generated by Django 5.1.1 on 2024-10-27 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_tracking", "0003_transaction_payment_method_alter_account_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookentry",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance_tracking.account",
            ),
        ),
        migrations.AlterField(
            model_name="bookentry",
            name="transaction",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance_tracking.transaction",
            ),
        ),
        migrations.AlterField(
            model_name="bookentry",
            name="user_account_balance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="finance_tracking.useraccountbalance",
            ),
        ),
    ]
