# Generated by Django 5.1.1 on 2024-09-27 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance_tracking", "0003_account_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={"ordering": ["-updated_at"]},
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="date",
        ),
    ]
