# Generated by Django 5.1.1 on 2024-10-27 19:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance_tracking", "0005_alter_useraccountbalance_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccountbalance",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
